//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORIS_AL.Models
{
    using System;
    
    public partial class UserSuppliers
    {
        public long UserID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public long UserSupplierID { get; set; }
    }
}
